Johngeorgesample/pgh-coffee

- app/components/ShopCard.tsx
- app/globals.css
- app/page.tsx
Introduces the ability to filter the list of shops by neighborhood or shop name
> [Feature] Add filtering

- data/coffee_shops.json
https://www.instagram.com/p/C1-0JGPt9zY
> Remove Adda

- app/components/Header.tsx
- app/page.tsx
What it says on the tin, plus I start to break components off from page.tsx
> [Bugfix] Fix 500s on page load

- app/page.tsx
> Better mobile styles

- app/about/page.tsx
- data/coffee_shops.json
The first pass at including shop outside city proper. Despite the name of this PR, some shops are in Oakmont, Cheswick, and Verona.
> North hills

- data/coffee_shops.json
Added new coffee shop to data
A new coffee shop, Bitty & Beau's, has been added to the coffee_shops.json file. The addition includes details such as name, neighborhood, website, address and geographical coordinates. This does not include a photo, as I do not have my own photo  available and do not want to risk using a copyrighted image.
> Add Bitty and Beau's

- data/coffee_shops.json
> Fix Queen Beans website

- app/page.tsx
Fixes #34. Not the cleanest approach but it works for now  ¯\_(ツ)_/¯
> Wait before setting currentShop to empty object when closing panel

- app/about/page.tsx
- app/components/Nav.tsx
- app/layout.tsx
- app/page.tsx
- app/settings/page.tsx
Instead of each component handling its own instance of `main` and `Nav`, this PR moves them to `Layout`
> Move common elements to Layout

- app/components/Nav.tsx
> Shrink the size of icons/text in nav

- app/about/page.tsx
- app/components/QAndA.tsx
> New /about styles

- app/api/shops/submit/route.ts
- app/components/Nav.tsx
- app/settings/page.tsx
- app/submit-a-shop/SuccessDialog.tsx
- app/submit-a-shop/page.tsx
Since you're no longer able to add shops via a PR, I needed a new way to accept user submissions.
Introduces new endpoint `POST /api/shops/submit`
> Submit a shop

- app/page.tsx
It's hard to hit the dots on mobile ¯\_(ツ)_/¯. This PR makes it so they'll slowly grow/shrink as you zoom in/out.
> Increase circle radius (aka shop dots) with zoom

- app/api/shops/geojson/route.ts
- app/api/shops/route.ts
It should have always been like this 🤦
> Order results of `/api/shops/` and `/api/shops/geojson/` by name

- app/api/shops/[shopDetails]/route.ts
- app/components/NearbyShops.tsx
- app/page.tsx
* Opening a shop appends a search param to the URL
* Visiting the site with a valid search param will open the panel with the shop's details
This will allow users to share direct links to shops.
https://github.com/user-attachments/assets/3f8ff5ea-fc1a-4abd-8551-db389bfdae88
> Append shop info to URL

- app/components/NearbyShops.tsx
- app/components/PanelContent.tsx
- app/components/ShopCard.tsx
- app/components/ShopDetails.tsx
- app/components/ShopList.tsx
- app/components/ShopPanel.tsx
- app/components/ShopSearch.tsx
- app/layout.tsx
- app/page.tsx
No user facing changes, just some code cleanup. Consolidates some repetitive JSX into components and shifts logic around so it can be reused.
> Add ShopList, ShopCard components and misc. refactorings

- app/page.tsx
Enables [custom properties](https://plausible.io/docs/custom-props/introduction) in Plausible. This will give better insight into user behavior that will help me to prioritize feature development.
> Custom properties

- app/components/NearbyShops.tsx
- app/components/ShopSearch.tsx
- app/page.tsx
I should have added these in https://github.com/Johngeorgesample/pgh-coffee/pull/86 but I jumped the gun.
> Custom properties for ShopSearch and NearbyShops

- app/components/ShopSearch.tsx
> Update search placeholder to mention `neighborhoods`

- app/components/NearbyShops.tsx
- app/components/PanelContent.tsx
- app/components/PanelFooter.tsx
Shops with no nearby shops, one nearby shop, and 2+ nearby shops all have the same layout/spacing.
This PR
Prod
> Predictable spacing in panel

- app/components/HomeClient.tsx
- app/components/MapContainer.tsx
- app/components/NearbyShops.tsx
- app/components/PanelContent.tsx
- app/components/PanelHeader.tsx
- app/components/ShopCard.tsx
- app/components/ShopDetails.tsx
- types/shop-types.ts
I plugged a few components into Deepseek's r1 and had it review the code. I incorporated the feedback I agreed with.
> Misc. refactoring

- app/components/HomeClient.tsx
- app/components/MapContainer.tsx
Implements the [extract method](https://refactoring.guru/extract-method) refactoring in a few components. No user-facing changes here, just readability improvements.
> Extract functions from useEffect
